/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_novedia_radiofrance_ffmpeg_Videokit */

#ifndef _Included_com_novedia_radiofrance_ffmpeg_Videokit
#define _Included_com_novedia_radiofrance_ffmpeg_Videokit
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_novedia_radiofrance_ffmpeg_Videokit_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
